Homework1
made-ml-in-prod-2022/arsen_kuzhamuratov pull request #1
Opened 2022-05-07 20:41 UTC by kuzhamuratov

__Машинное обучение__: 
- а) проведен анализ данных и кодировка полезных признаков;
- б) обучены модели Градиентного бустинга над деревьями и Логистическая регрессия;
- в) обученные модели, статистики для кодировки и нормализации признаков на входе, а также предсказания сохраняются в отдельную папку;
-  г) все этапы логируются в отдельный файл и выводятся на консоль.

__Код__:  
- анализ данных  `EDA_analysis.ipynb`;
- конфиги для моделей `configs/`;
-  `main.py` - запуск обучения и тестирования;
-  `utils.py` - основные методы и классы;
-  `data/` - данные для обучения и тестирования (без настройки скачивания или внешнего хранилища);
- `outputs/` - папка для сохранения моделей, статистик для кодировки и нормализации признаков, предсказаний;
- `tests/` - папка с юниттестами и тестами всего обучения и тестирования;
- в `README.md` приведен код для запуска обучения/тестирования и отображено дерево проекта.

- [X] В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код (1 балл)
- [X] В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (1 балл)
- [X] Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл)
- [X] Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла)
- [X] Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла)
- [X] Проект имеет модульную структуру (2 балла)
- [X] Использованы логгеры (2 балла)
- [X] Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла)
- [ ] Для тестов генерируются синтетические данные, приближенные к реальным (2 балла)
- [X] Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)
- [ ] Используются датаклассы для сущностей из конфига, а не голые dict (2 балла)
- [ ] Напишите кастомный трансформер и протестируйте его (3 балла) 
- [X] В проекте зафиксированы все зависимости (1 балл)
- [X] Настроен CI для прогона тестов, линтера на основе github actions (3 балла)

2022-05-18 18:52 UTC, SVizor42 commented on ml_project/main.py
> +from ml_project.config import ModelCfg
В первую очередь импортируются стандартные пакеты, а затем уже локальные (см. pep-8)

2022-05-18 19:48 UTC, SVizor42 commented on ml_project/utils.py
> +def divide_columns_by_type(data, threshold=10):
Думаю, проще все-таки было сделать через файл конфига для признаков

2022-05-18 19:50 UTC, SVizor42 commented on ml_project/utils.py
> +    if 'condition' in data.columns:
Наименования колонок все-таки не стоит хардкодить

2022-05-18 19:52 UTC, SVizor42 commented on ml_project/utils.py
> +    if model_type == 'GradientBoosting':
Бустинг без предобработки данных?

2022-05-18 20:29 UTC, SVizor42 requested changes
Проведен хороший EDA и прототипирование в ноутбуке. За это +
Что точно нужно поправить:
1. Typing: практически нигде не указаны типы у аргументов и возвращаемых значений функций.
2. Модульность - фактически весь код расположен в `main.py` и `utils.py` (который содержит и функции обработки данных, и класс Модели и т.д.). Лучше разнести по разным модулям.

Комментарии по основным архитектурным решениям (принять к сведению, исправлять на свое усмотрение):
1. Для удобства я бы предложил разделять конфиги для обучения и инференса.
2. Перечень признаков (числовых, категориальных и т.д.) и таргет лучше вынести в конфиг. Тогда пропадет необходимость самостоятельно определять тип признака и хардкодить какие-то фичи.
3. Опять таки есть самописный Scaler и OHE. Можно было бы обернуть это в отдельный класс, определить основные методы - и вот готовый кастомный трансформер.
4. Используя этот трансформер можно было бы построить пайплайн и сохранять/загружать веса моделей.
5. В коде практически отсутствуют докстринги.

2022-05-22 09:17 UTC, kuzhamuratov commented on ml_project/main.py
> +from ml_project.config import ModelCfg
Импорты упорядочил: сначала стандартные пакеты, затем пакеты установленные через pip3/conda, далее локальные.

2022-05-22 09:18 UTC, kuzhamuratov commented on ml_project/utils.py
> +def divide_columns_by_type(data, threshold=10):
Да, согласен. Но пока оставлю так.

2022-05-22 09:18 UTC, kuzhamuratov commented on ml_project/utils.py
> +    if 'condition' in data.columns:
Вынес в начало файла в виде констант.

2022-05-22 09:20 UTC, kuzhamuratov commented on ml_project/utils.py
> +    if model_type == 'GradientBoosting':
Да, признаки не генерировал. Данных мало (300 строк), я посчитал, что логрегрессия лучше всего подходит.

2022-05-22 09:28 UTC, kuzhamuratov commented
@SVizor42 , привет. Спасибо за описание ошибок и исправлений. 

По поводу исправлений:
1) Добавил везде `Typing `аргументов и `docstrings`.
2) Разнес код по разным модулям:  модель в `model/`, метрики в `metrics/`, генерацию признаков в `feature_extraction/`.

По поводу комментариев:
- поздно заметил пункт с трансформером;
- добавил везде `docstrings`;
- пункты 1 и 2 нет времени сделать, так же как и трансформер =(

2022-05-22 14:40 UTC, SVizor42 approved these changes
Все ок.
**Сумма: 29 баллов** (пункт с кастомным трансформером не учитываем).
Перед мерджем ветки лучше создать отдельную папку для ДЗ1 и вложить туда файлы, т.к. остальные ДЗ нужно будет класть сюда же.

2022-05-22 15:29 UTC, merged